### ISSUE TITLE
Using io.branch.sdk.android:library-2.15.0 Couldn't Build with Proguard

### ISSUE THREAD

**Issue by drayan85** [BranchMetrics/Branch-Example-Deep-Linking-Branchster-Android#18]
```
Information:Gradle tasks [:app:assembleProductionRelease]
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find superclass or interface com.android.installreferrer.api.InstallReferrerStateListener
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.InstallReferrerStateListener
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.InstallReferrerClient
Warning:io.branch.referral.InstallListener$ReferrerClientWrapper$1: can't find referenced class com.android.installreferrer.api.ReferrerDetails
Warning:there were 9 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForProductionRelease'.
> Job failed, see logs for details
Information:BUILD FAILED in 31s
Information:1 error
Information:6 warnings
Information:See complete output in console
```

I was able to build with previous version.

**Comment by kanak86** [comment]
Could you find any solution to this issue?

**Comment by drayan85** [comment]
Add the `-dontwarn com.android.installreferrer.api.**` to your proguard rules to remove the warnings.
You can Find the Documentation about this settings in [Here](https://github.com/BranchMetrics/android-branch-deep-linking#proguard-warning-or-errors-with-appindexing-module)
> ### Proguard warning or errors with `appindexing` module
> Branch SDK has optional dependencies on Firebase app indexing and Android install referrer classes to provide new Firebase content listing features and support new Android install referrer library. This may cause a proguard warning depending on your proguard settings.
Please add the following to your proguard file to solve this issue
`-dontwarn com.google.firebase.appindexing.**`
`-dontwarn com.android.installreferrer.api.**`
